use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize, Default)]
pub struct ThemeConfig {
    pub primary: Option<String>,
    pub on_primary: Option<String>,
    pub primary_container: Option<String>,
    pub on_primary_container: Option<String>,
    pub secondary: Option<String>,
    pub on_secondary: Option<String>,
    pub secondary_container: Option<String>,
    pub on_secondary_container: Option<String>,
    pub tertiary: Option<String>,
    pub on_tertiary: Option<String>,
    pub tertiary_container: Option<String>,
    pub on_tertiary_container: Option<String>,
    pub error: Option<String>,
    pub on_error: Option<String>,
    pub error_container: Option<String>,
    pub on_error_container: Option<String>,
    pub background: Option<String>,
    pub on_background: Option<String>,
    pub surface: Option<String>,
    pub on_surface: Option<String>,
    pub surface_variant: Option<String>,
    pub on_surface_variant: Option<String>,
    pub outline: Option<String>,
    pub outline_variant: Option<String>,
    pub shadow: Option<String>,
    pub scrim: Option<String>,
    pub inverse_surface: Option<String>,
    pub inverse_on_surface: Option<String>,
    pub inverse_primary: Option<String>,
    pub surface_container_lowest: Option<String>,
    pub surface_container_low: Option<String>,
    pub surface_container: Option<String>,
    pub surface_container_high: Option<String>,
    pub surface_container_highest: Option<String>,
}
